### ISSUE TITLE
Roadmap for Reincarnation 2.0's release

### ISSUE THREAD

**Issue by cubebert-github** [Samsara-Reincarnation/Samsara-Reincarnation#161]
There's a lot of stuff we need to fix and tweak before Samsara Reincarnation 2.0's late-September release date. There's some stuff that will likely be moved to either 2.0a or 2.1's release, but there should be a list to keep track of the things that need to be added or polished.

- [x] Add in the Compendium entries for the new classes
- [x] Finish up the Dark Side AI enemies for the new classes and get them working
- [x] Finish writing the Compendium entries for the new settings
- [x] Fix Instagib Mode (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/145)
- [x] Fix Unreal bullet spark animation (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/155)
- [x] Finish moving a few of Stronghold Doomguy's weapons to the extra slots (Auto Shotgun, Flamethrower, Mines, Stunner Rifle, Pyro Cannon)
- [x] Remove all of the startup errors (excluding the ones from the Pyro-GX's MODELDEF)
- [x] Finish getting sounds for the Strife Talismans and the Raven Chaos Devices
- [x] Move some of the extra weapons to ST slots. It makes little sense not to for some of these...
- [x] Add Denton's missing taunts and talk

There's much more to do than what's on this list, but it should be a good starting point for our goal.
