### ISSUE TITLE
Roadmap for Reincarnation 2.1's release

### ISSUE THREAD

**Issue by cubebert-github** [Samsara-Reincarnation/Samsara-Reincarnation#162]
For Reincarnation 2.1, we'll be hosting an open beta once we implement a few stuff that went to the cutting-room floor for 2.0. This will include the following:

- [ ] Get the Eradicator altclasses working along with their Dark Side versions (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/134)
- [x] Finish the ammo switching animations for Duke64
- [x] Fix any bugs found after 2.0's release
- [ ] Fix oddities with the Painkiller weapon when using the altfire mode
- [ ] Add in a monster base for player allies and make them play better
- [x] Add in the Blood Proximity and Remote Dynamites
- [x] Do any other polishes and fixes

Afterwards, we should be free to add in the major features for 2.1.

- [ ] Implement the Macintosh and Jaguar B.J. altclasses from meleemario and tehvappy50
- [ ] Start work on the Outlaws class
- [x] Improve the organization and naming of the folders in the pk3
- [ ] Rename many actors to improve TC and custom IWAD compatibility
- [ ] Rename actors with improper actor names like "  Pistol  " to use more conventional names
- [ ] Add an option for straight projectiles with certain Slot V weapons (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/153)
- [ ] Find a way to show the amount of time left on Eleena's WEC (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/152)
- [ ] Improve Grondoval in competitive gamemodes (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/157)
- [ ] Make a separate tarot card menu for deathmatch (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/158)
- [ ] Implement Hexen 2 altclasses (https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/133)
- [ ] Separate the weapon pickup messages for extra weapons (Stronghold autoshotgun, Goldeneye Golden Gun, etc.)
- [ ] Re-add the "Everybody Rocket Jumps" serverside setting
- [ ] Redo the Freeman model stuff and put it in the player models external PK3
- [X] Work on the player class tip system for every class
- [ ] Add in a feature to ban altclasses from the server without touching the main classes
- [ ] Add in a toggle to prevent switching altclasses once the game starts
- [x] Normalize the colorization on some messages (obituaries, character ban messages, bot names, etc.)
- [ ] Rework Lo Wang to make his coding better and easier to work with
- [x] Rework Kyle Katarn to make him more accurate to his source game
- [x] Add in the Duke64 player sprites
- [ ] Implement a toggle to disable total gibbing for enemies (Quake gibbing, Duke3D gibbing for TotalGib monsters, etc.)
- [x] Finish the rest of the Raven powerups and the Skulltag powerups
- [ ] Add in a Scavenger pickup system for health items (As requested by Shiny Metagross; he'll know what that means)
- [ ] Work on compatibility settings that will make heroes be able to work on certain maps that need it or function more accurately to their game (Stuff like [this](https://github.com/Samsara-Reincarnation/Samsara-Reincarnation/issues/153) or an option to allow players to set off their own mines for example)
- [x] Add in exit messages from the games represented by the new heroes
